"""KabuAI-Daytrade Pydantic models for the entire system."""

import uuid
from datetime import datetime, date as date_type
from typing import Literal, Optional

from pydantic import BaseModel, Field


def _new_id() -> str:
    return uuid.uuid4().hex[:12]


class TradeSignal(BaseModel):
    """Signal generated by a strategy recommending a trade entry."""

    strategy_name: str
    ticker: str
    direction: Literal["long", "short"]
    entry_price: float
    stop_loss: float
    take_profit: float
    confidence: float = Field(ge=0.0, le=1.0)
    timestamp: datetime = Field(default_factory=datetime.now)
    features_snapshot: dict = Field(default_factory=dict)
    entry_reason: str = ""


class Position(BaseModel):
    """An open position currently held."""

    id: str = Field(default_factory=_new_id)
    ticker: str
    strategy_name: str
    direction: Literal["long", "short"]
    entry_price: float
    entry_time: datetime
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    holding_minutes: int = 0
    stop_loss: float = 0.0
    take_profit: float = 0.0


class TradeResult(BaseModel):
    """Completed trade with full entry/exit details."""

    id: str = Field(default_factory=_new_id)
    ticker: str
    strategy_name: str
    direction: Literal["long", "short"]
    entry_price: float
    exit_price: float
    entry_time: datetime
    exit_time: datetime
    pnl: float = 0.0
    pnl_pct: float = 0.0
    holding_minutes: int = 0
    entry_reason: str = ""
    exit_reason: str = ""
    features_at_entry: dict = Field(default_factory=dict)
    features_at_exit: dict = Field(default_factory=dict)
    market_condition: str = ""


class StrategyPerformance(BaseModel):
    """Aggregated performance metrics for a strategy."""

    strategy_name: str
    total_trades: int = 0
    wins: int = 0
    losses: int = 0
    win_rate: float = 0.0
    profit_factor: float = 0.0
    avg_pnl: float = 0.0
    avg_holding_minutes: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0
    performance_by_condition: dict = Field(default_factory=dict)
    performance_by_event: dict = Field(default_factory=dict)
    last_updated: datetime = Field(default_factory=datetime.now)


class StrategyConfig(BaseModel):
    """Configuration and parameters for a trading strategy."""

    strategy_name: str
    entry_conditions: dict = Field(default_factory=dict)
    exit_conditions: dict = Field(default_factory=dict)
    expected_market_condition: str = ""
    feature_requirements: list[str] = Field(default_factory=list)
    parameter_set: dict = Field(default_factory=dict)
    is_active: bool = True
    version: str = "1.0.0"


class MarketCondition(BaseModel):
    """Snapshot of overall market conditions at a point in time."""

    timestamp: datetime = Field(default_factory=datetime.now)
    nikkei225_change_pct: float = 0.0
    topix_change_pct: float = 0.0
    usd_jpy: float = 0.0
    vix: float = 0.0
    market_regime: Literal["bull", "bear", "range", "volatile"] = "range"
    sector_momentum: dict = Field(default_factory=dict)


class KnowledgeEntry(BaseModel):
    """A piece of learning extracted from trading activity."""

    id: str = Field(default_factory=_new_id)
    date: date_type = Field(default_factory=date_type.today)
    category: Literal[
        "win_pattern", "loss_pattern", "strategy_insight", "market_insight"
    ]
    content: str
    supporting_trades: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0, default=0.5)
    auto_generated: bool = False


class CandidateUpdate(BaseModel):
    """A proposed change to a strategy awaiting review."""

    id: str = Field(default_factory=_new_id)
    strategy_name: str
    proposed_changes: dict = Field(default_factory=dict)
    reason: str = ""
    expected_improvement: str = ""
    status: Literal["pending", "approved", "rejected", "applied"] = "pending"
    created_at: datetime = Field(default_factory=datetime.now)
    reviewed_at: datetime | None = None


class Order(BaseModel):
    """A trading order submitted to the broker."""

    id: str = Field(default_factory=_new_id)
    ticker: str
    direction: Literal["long", "short"]
    order_type: str = "market"
    price: float = 0.0
    quantity: int = 0
    status: str = "pending"
    strategy_name: str = ""
    timestamp: datetime = Field(default_factory=datetime.now)


class DailyReport(BaseModel):
    """End-of-day summary report."""

    date: date_type = Field(default_factory=date_type.today)
    total_pnl: float = 0.0
    total_trades: int = 0
    win_rate: float = 0.0
    best_trade: Optional[str] = None
    worst_trade: Optional[str] = None
    strategy_summary: dict = Field(default_factory=dict)
    knowledge_entries: list = Field(default_factory=list)
    improvement_candidates: list = Field(default_factory=list)
